plugins {
    id 'java'
    id 'maven-publish'
}

group 'ru.chugunov'
version '1.2-SNAPSHOT'

repositories {
    mavenCentral()
    mavenLocal()
}

compileJava.options.encoding = 'UTF-8'

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

def springVersion = '3.2.5'

dependencies {
    implementation "org.springframework.boot:spring-boot-starter-web:${springVersion}"
    implementation "org.springframework.boot:spring-boot-starter-aop:${springVersion}"

}

test {
    useJUnitPlatform()
}

publishing {
    publications {
        maven (MavenPublication) {
            groupId = rootProject.getGroup()
            artifactId = rootProject.getName()
            version = rootProject.getVersion()

            from components.java
        }
    }

    repositories {
        maven {
            url = "file://${project.projectDir.toString()}/maven-repo/"
        }
    }
}